### ISSUE TITLE
history mismatch?

### ISSUE THREAD

**Issue by pepdiz** [mittelmark/shtmlview#5]
[ej.txt](https://github.com/mittelmark/shtmlview/files/8290158/ej.txt)

The problem is described in the file attached (ej.txt) 

When you run it like   `$ tclsh ej.txt`  in shtmlview directory (my) expected behaviour is:

1- you get an error trying to open non existent file index.html
2- you open and browse file shtmlview.html
3- you open and browse README.md

but output is :

```
C:\Downloads\shtmlview>tclsh ej.tcl
You browsed C:/Downloads/shtmlview/shtmlview.html
H: C:/Downloads/shtmlview/shtmlview.html
F: C:/Downloads/shtmlview/shtmlview.html
```
and if you dropdownd the history combo list there are two files in history

I undertand both files from steps (2) and (3) are added to history but only file (2) , first file, is rendered in the widget, that is, you choose to render the first file browsed rather than the last one (the first file indicated in browser list passed to command browse),  that's ok, you can choose first file or last one. 

History list has two files, so you can see two files in history combo and you see the first one rendered because the first one is the one you has visited, and thus the browsecmd binded receives that first visited file as url parameter.

But what I find disturbing is inside the browsecmd proc, a call to getHistory gives me only one file as you can see in output line "H: ..."  while history combo lists two files. Also a call to getFiles gives only one files, but this is supposed to return opened files, thus two files.   You can see this behaviour in attached image.

![scr1-2files browsed](https://user-images.githubusercontent.com/4483195/158886023-54785224-310f-4936-8f37-48ba71073497.png)

**Comment by pepdiz** [comment]
Also when I go back in history to the first file (shtmlview.html) and close it using the toolbar button,  I got only one file in history combo (the remaining one) and also as return value of getHistory command, but I got two files when calling getFiles command, as you can see in attached image and in the output

```
You browsed C:/Downloads/shtmlview/README.md
H: C:/Downloads/shtmlview/README.md
F: C:/Downloads/shtmlview/shtmlview.html C:/Downloads/shtmlview/README.md
```

I assume history is tracking the files visited in the order you visit them while files is tracking the history of opened files, but it's a bit confusing. 

Wouldn't be better to have only a history list?

![scr2-1file closed](https://user-images.githubusercontent.com/4483195/158887603-97264145-898a-47ca-88b3-c7663266adbf.png)

**Comment by mittelmark** [comment]
There is currently a mixture of concepts, open files and history. Currently if you browse multiple files ($help browse file1.html file2.html file3.md) they should be all added to the history, but only the first one in history should be shown. That allows to walk simply forward and look at all the files using the f-key or go back using the b-key. That is what should be shown in the optional drop-down menu on top. files are all files which are currently part of the history. If you drop a history item you might as well drop as well the file if it is just once mentioned in the history. That is currently the design, If you call browse on a file it is in the history, if you call browse on many files, they are all in the history, but there might some issues in synchronizing. At least that is what your example on top shows. I will look into getFiles and getHistory.

**Comment by mittelmark** [comment]
The mismatch should be gone now, there was a problem with synchronization, files where not browsed yet, but already in the history stack. The stack however was filled after the browsing. Now it should be fine.
